namespace EM.Database.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateDatabase : DbMigration
    {
        public override void Up()
        {
            RenameColumn(table: "dbo.Account", name: "IdGroup", newName: "GroupId");
            RenameColumn(table: "dbo.Account", name: "IdUser", newName: "UserId");
            RenameColumn(table: "dbo.Permission", name: "IdGroup", newName: "GroupId");
            RenameColumn(table: "dbo.Permission", name: "IdFunction", newName: "FunctionId");
            RenameColumn(table: "dbo.Function", name: "IdScreen", newName: "ScreenId");
            RenameColumn(table: "dbo.Notification", name: "IdReceiver", newName: "ReceiverId");
            RenameColumn(table: "dbo.Notification", name: "IdSender", newName: "SenderId");
            RenameColumn(table: "dbo.Parent", name: "IdUser", newName: "UserId");
            RenameColumn(table: "dbo.Student", name: "IdUser", newName: "UserId");
            RenameColumn(table: "dbo.Teacher", name: "IdUser", newName: "UserId");
            RenameColumn(table: "dbo.Notification", name: "IdClassReceiver", newName: "ClassReceiverId");
            RenameColumn(table: "dbo.Class", name: "IdGrade", newName: "GradeId");
            RenameColumn(table: "dbo.Class", name: "IdRoom", newName: "RoomId");
            RenameColumn(table: "dbo.ScheduleSubject", name: "IdClass", newName: "ClassId");
            RenameColumn(table: "dbo.Student", name: "IdClass", newName: "ClassId");
            RenameColumn(table: "dbo.Class", name: "IdTeacher", newName: "TeacherId");
            RenameColumn(table: "dbo.ScheduleSubject", name: "IdDayLesson", newName: "DayLessonId");
            RenameColumn(table: "dbo.ScheduleSubject", name: "IdSubject", newName: "SubjectId");
            RenameColumn(table: "dbo.ScheduleSubject", name: "IdTeacher", newName: "TeacherId");
            RenameColumn(table: "dbo.SubjectMark", name: "IdSubject", newName: "SubjectId");
            RenameColumn(table: "dbo.Subject", name: "IdTeam", newName: "TeamId");
            RenameColumn(table: "dbo.SubjectMark", name: "IdSemester", newName: "SemesterId");
            RenameColumn(table: "dbo.SubjectMark", name: "IdStudent", newName: "StudentId");
            RenameColumn(table: "dbo.SubjectMark", name: "IdTypeMark", newName: "TypeMarkId");
            RenameColumn(table: "dbo.Semester", name: "IdScholastic", newName: "ScholasticId");
            RenameColumn(table: "dbo.StudentTranscript", name: "IdSemester", newName: "SemesterId");
            RenameColumn(table: "dbo.Result", name: "IdScholastic", newName: "ScholasticId");
            RenameColumn(table: "dbo.Result", name: "IdClassification", newName: "ClassificationId");
            RenameColumn(table: "dbo.Result", name: "IdConduct", newName: "ConductId");
            RenameColumn(table: "dbo.Result", name: "IdStudent", newName: "StudentId");
            RenameColumn(table: "dbo.StudentTranscript", name: "IdClassification", newName: "ClassificationId");
            RenameColumn(table: "dbo.StudentTranscript", name: "IdConduct", newName: "ConductId");
            RenameColumn(table: "dbo.StudentTranscript", name: "IdStudent", newName: "StudentId");
            RenameColumn(table: "dbo.Student", name: "IdParent", newName: "ParentId");
            RenameColumn(table: "dbo.Teacher", name: "IdTeam", newName: "TeamId");
            RenameIndex(table: "dbo.Account", name: "IX_IdUser", newName: "IX_UserId");
            RenameIndex(table: "dbo.Account", name: "IX_IdGroup", newName: "IX_GroupId");
            RenameIndex(table: "dbo.Permission", name: "IX_IdGroup", newName: "IX_GroupId");
            RenameIndex(table: "dbo.Permission", name: "IX_IdFunction", newName: "IX_FunctionId");
            RenameIndex(table: "dbo.Function", name: "IX_IdScreen", newName: "IX_ScreenId");
            RenameIndex(table: "dbo.Notification", name: "IX_IdSender", newName: "IX_SenderId");
            RenameIndex(table: "dbo.Notification", name: "IX_IdReceiver", newName: "IX_ReceiverId");
            RenameIndex(table: "dbo.Notification", name: "IX_IdClassReceiver", newName: "IX_ClassReceiverId");
            RenameIndex(table: "dbo.Class", name: "IX_IdGrade", newName: "IX_GradeId");
            RenameIndex(table: "dbo.Class", name: "IX_IdRoom", newName: "IX_RoomId");
            RenameIndex(table: "dbo.Class", name: "IX_IdTeacher", newName: "IX_TeacherId");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_IdDayLesson", newName: "IX_DayLessonId");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_IdSubject", newName: "IX_SubjectId");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_IdClass", newName: "IX_ClassId");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_IdTeacher", newName: "IX_TeacherId");
            RenameIndex(table: "dbo.Subject", name: "IX_IdTeam", newName: "IX_TeamId");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_IdTypeMark", newName: "IX_TypeMarkId");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_IdStudent", newName: "IX_StudentId");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_IdSubject", newName: "IX_SubjectId");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_IdSemester", newName: "IX_SemesterId");
            RenameIndex(table: "dbo.Semester", name: "IX_IdScholastic", newName: "IX_ScholasticId");
            RenameIndex(table: "dbo.Result", name: "IX_IdStudent", newName: "IX_StudentId");
            RenameIndex(table: "dbo.Result", name: "IX_IdClassification", newName: "IX_ClassificationId");
            RenameIndex(table: "dbo.Result", name: "IX_IdConduct", newName: "IX_ConductId");
            RenameIndex(table: "dbo.Result", name: "IX_IdScholastic", newName: "IX_ScholasticId");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_IdStudent", newName: "IX_StudentId");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_IdClassification", newName: "IX_ClassificationId");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_IdConduct", newName: "IX_ConductId");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_IdSemester", newName: "IX_SemesterId");
            RenameIndex(table: "dbo.Student", name: "IX_IdUser", newName: "IX_UserId");
            RenameIndex(table: "dbo.Student", name: "IX_IdClass", newName: "IX_ClassId");
            RenameIndex(table: "dbo.Student", name: "IX_IdParent", newName: "IX_ParentId");
            RenameIndex(table: "dbo.Parent", name: "IX_IdUser", newName: "IX_UserId");
            RenameIndex(table: "dbo.Teacher", name: "IX_IdUser", newName: "IX_UserId");
            RenameIndex(table: "dbo.Teacher", name: "IX_IdTeam", newName: "IX_TeamId");
            AddColumn("dbo.Account", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Account", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Account", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Account", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Group", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Group", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Group", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Group", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Group", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Permission", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Permission", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Permission", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Permission", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Function", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Function", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Function", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Function", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Function", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Screen", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Screen", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Screen", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Screen", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Screen", "UpdatedBy", c => c.Int());
            AddColumn("dbo.User", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.User", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.User", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.User", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Notification", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Notification", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Notification", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Notification", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Class", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Class", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Class", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Class", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Class", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Grade", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Grade", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Grade", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Grade", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Grade", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Room", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Room", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Room", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Room", "UpdatedBy", c => c.Int());
            AddColumn("dbo.ScheduleSubject", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.ScheduleSubject", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.ScheduleSubject", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.ScheduleSubject", "UpdatedBy", c => c.Int());
            AddColumn("dbo.DayOfWeekLesson", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.DayOfWeekLesson", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.DayOfWeekLesson", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.DayOfWeekLesson", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Subject", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Subject", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Subject", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Subject", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Subject", "UpdatedBy", c => c.Int());
            AddColumn("dbo.SubjectMark", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.SubjectMark", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.SubjectMark", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.SubjectMark", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Semester", "Name", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Semester", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Semester", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Semester", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Semester", "UpdatedBy", c => c.Int());
            AddColumn("dbo.SchoolYear", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.SchoolYear", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.SchoolYear", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.SchoolYear", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Result", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Result", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Result", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Result", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Classification", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Classification", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Classification", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Classification", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Classification", "UpdatedBy", c => c.Int());
            AddColumn("dbo.StudentTranscript", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.StudentTranscript", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.StudentTranscript", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.StudentTranscript", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Conduct", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Conduct", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Conduct", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Conduct", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Student", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Student", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Student", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Student", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Parent", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Parent", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Parent", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Parent", "UpdatedBy", c => c.Int());
            AddColumn("dbo.TypeMark", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.TypeMark", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.TypeMark", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.TypeMark", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.TypeMark", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Team", "Name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Team", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Team", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Team", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Team", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Teacher", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Teacher", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Teacher", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Teacher", "UpdatedBy", c => c.Int());
            AddColumn("dbo.ErrorMessage", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.ErrorMessage", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.ErrorMessage", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.ErrorMessage", "UpdatedBy", c => c.Int());
            AddColumn("dbo.News", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.News", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.News", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.News", "UpdatedBy", c => c.Int());
            AddColumn("dbo.SchoolInformation", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.SchoolInformation", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.SchoolInformation", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.SchoolInformation", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Slide", "CreatedAt", c => c.DateTime());
            AddColumn("dbo.Slide", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Slide", "UpdatedAt", c => c.DateTime());
            AddColumn("dbo.Slide", "UpdatedBy", c => c.Int());
            DropColumn("dbo.Account", "Token");
            DropColumn("dbo.Account", "Created_at");
            DropColumn("dbo.Account", "Created_by");
            DropColumn("dbo.Account", "Updated_at");
            DropColumn("dbo.Account", "Updated_by");
            DropColumn("dbo.Group", "GroupName");
            DropColumn("dbo.Group", "Created_at");
            DropColumn("dbo.Group", "Created_by");
            DropColumn("dbo.Group", "Updated_at");
            DropColumn("dbo.Group", "Updated_by");
            DropColumn("dbo.Permission", "Created_at");
            DropColumn("dbo.Permission", "Created_by");
            DropColumn("dbo.Permission", "Updated_at");
            DropColumn("dbo.Permission", "Updated_by");
            DropColumn("dbo.Function", "FunctionName");
            DropColumn("dbo.Function", "Created_at");
            DropColumn("dbo.Function", "Created_by");
            DropColumn("dbo.Function", "Updated_at");
            DropColumn("dbo.Function", "Updated_by");
            DropColumn("dbo.Screen", "ScreenName");
            DropColumn("dbo.Screen", "Created_at");
            DropColumn("dbo.Screen", "Created_by");
            DropColumn("dbo.Screen", "Updated_at");
            DropColumn("dbo.Screen", "Updated_by");
            DropColumn("dbo.User", "Created_at");
            DropColumn("dbo.User", "Created_by");
            DropColumn("dbo.User", "Updated_at");
            DropColumn("dbo.User", "Updated_by");
            DropColumn("dbo.Notification", "Created_at");
            DropColumn("dbo.Notification", "Created_by");
            DropColumn("dbo.Notification", "Updated_at");
            DropColumn("dbo.Notification", "Updated_by");
            DropColumn("dbo.Class", "ClassName");
            DropColumn("dbo.Class", "Created_at");
            DropColumn("dbo.Class", "Created_by");
            DropColumn("dbo.Class", "Updated_at");
            DropColumn("dbo.Class", "Updated_by");
            DropColumn("dbo.Grade", "GradeName");
            DropColumn("dbo.Grade", "Created_at");
            DropColumn("dbo.Grade", "Created_by");
            DropColumn("dbo.Grade", "Updated_at");
            DropColumn("dbo.Grade", "Updated_by");
            DropColumn("dbo.Room", "Created_at");
            DropColumn("dbo.Room", "Created_by");
            DropColumn("dbo.Room", "Updated_at");
            DropColumn("dbo.Room", "Updated_by");
            DropColumn("dbo.ScheduleSubject", "Created_at");
            DropColumn("dbo.ScheduleSubject", "Created_by");
            DropColumn("dbo.ScheduleSubject", "Updated_at");
            DropColumn("dbo.ScheduleSubject", "Updated_by");
            DropColumn("dbo.DayOfWeekLesson", "Created_at");
            DropColumn("dbo.DayOfWeekLesson", "Created_by");
            DropColumn("dbo.DayOfWeekLesson", "Updated_at");
            DropColumn("dbo.DayOfWeekLesson", "Updated_by");
            DropColumn("dbo.Subject", "SubjectName");
            DropColumn("dbo.Subject", "Created_at");
            DropColumn("dbo.Subject", "Created_by");
            DropColumn("dbo.Subject", "Updated_at");
            DropColumn("dbo.Subject", "Updated_by");
            DropColumn("dbo.SubjectMark", "Created_at");
            DropColumn("dbo.SubjectMark", "Created_by");
            DropColumn("dbo.SubjectMark", "Updated_at");
            DropColumn("dbo.SubjectMark", "Updated_by");
            DropColumn("dbo.Semester", "SemesterName");
            DropColumn("dbo.Semester", "Created_at");
            DropColumn("dbo.Semester", "Created_by");
            DropColumn("dbo.Semester", "Updated_at");
            DropColumn("dbo.Semester", "Updated_by");
            DropColumn("dbo.SchoolYear", "Created_at");
            DropColumn("dbo.SchoolYear", "Created_by");
            DropColumn("dbo.SchoolYear", "Updated_at");
            DropColumn("dbo.SchoolYear", "Updated_by");
            DropColumn("dbo.Result", "Created_at");
            DropColumn("dbo.Result", "Created_by");
            DropColumn("dbo.Result", "Updated_at");
            DropColumn("dbo.Result", "Updated_by");
            DropColumn("dbo.Classification", "NameClassification");
            DropColumn("dbo.Classification", "Created_at");
            DropColumn("dbo.Classification", "Created_by");
            DropColumn("dbo.Classification", "Updated_at");
            DropColumn("dbo.Classification", "Updated_by");
            DropColumn("dbo.StudentTranscript", "Created_at");
            DropColumn("dbo.StudentTranscript", "Created_by");
            DropColumn("dbo.StudentTranscript", "Updated_at");
            DropColumn("dbo.StudentTranscript", "Updated_by");
            DropColumn("dbo.Conduct", "Created_at");
            DropColumn("dbo.Conduct", "Created_by");
            DropColumn("dbo.Conduct", "Updated_at");
            DropColumn("dbo.Conduct", "Updated_by");
            DropColumn("dbo.Student", "Created_at");
            DropColumn("dbo.Student", "Created_by");
            DropColumn("dbo.Student", "Updated_at");
            DropColumn("dbo.Student", "Updated_by");
            DropColumn("dbo.Parent", "Created_at");
            DropColumn("dbo.Parent", "Created_by");
            DropColumn("dbo.Parent", "Updated_at");
            DropColumn("dbo.Parent", "Updated_by");
            DropColumn("dbo.TypeMark", "NameTypeMark");
            DropColumn("dbo.TypeMark", "Created_at");
            DropColumn("dbo.TypeMark", "Created_by");
            DropColumn("dbo.TypeMark", "Updated_at");
            DropColumn("dbo.TypeMark", "Updated_by");
            DropColumn("dbo.Team", "NameTeam");
            DropColumn("dbo.Team", "Created_at");
            DropColumn("dbo.Team", "Created_by");
            DropColumn("dbo.Team", "Updated_at");
            DropColumn("dbo.Team", "Updated_by");
            DropColumn("dbo.Teacher", "Created_at");
            DropColumn("dbo.Teacher", "Created_by");
            DropColumn("dbo.Teacher", "Updated_at");
            DropColumn("dbo.Teacher", "Updated_by");
            DropColumn("dbo.ErrorMessage", "Created_at");
            DropColumn("dbo.ErrorMessage", "Created_by");
            DropColumn("dbo.ErrorMessage", "Updated_at");
            DropColumn("dbo.ErrorMessage", "Updated_by");
            DropColumn("dbo.News", "Created_at");
            DropColumn("dbo.News", "Created_by");
            DropColumn("dbo.News", "Updated_at");
            DropColumn("dbo.News", "Updated_by");
            DropColumn("dbo.SchoolInformation", "Created_at");
            DropColumn("dbo.SchoolInformation", "Created_by");
            DropColumn("dbo.SchoolInformation", "Updated_at");
            DropColumn("dbo.SchoolInformation", "Updated_by");
            DropColumn("dbo.Slide", "Created_at");
            DropColumn("dbo.Slide", "Created_by");
            DropColumn("dbo.Slide", "Updated_at");
            DropColumn("dbo.Slide", "Updated_by");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Slide", "Updated_by", c => c.Int());
            AddColumn("dbo.Slide", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Slide", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Slide", "Created_at", c => c.DateTime());
            AddColumn("dbo.SchoolInformation", "Updated_by", c => c.Int());
            AddColumn("dbo.SchoolInformation", "Updated_at", c => c.DateTime());
            AddColumn("dbo.SchoolInformation", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.SchoolInformation", "Created_at", c => c.DateTime());
            AddColumn("dbo.News", "Updated_by", c => c.Int());
            AddColumn("dbo.News", "Updated_at", c => c.DateTime());
            AddColumn("dbo.News", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.News", "Created_at", c => c.DateTime());
            AddColumn("dbo.ErrorMessage", "Updated_by", c => c.Int());
            AddColumn("dbo.ErrorMessage", "Updated_at", c => c.DateTime());
            AddColumn("dbo.ErrorMessage", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.ErrorMessage", "Created_at", c => c.DateTime());
            AddColumn("dbo.Teacher", "Updated_by", c => c.Int());
            AddColumn("dbo.Teacher", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Teacher", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Teacher", "Created_at", c => c.DateTime());
            AddColumn("dbo.Team", "Updated_by", c => c.Int());
            AddColumn("dbo.Team", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Team", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Team", "Created_at", c => c.DateTime());
            AddColumn("dbo.Team", "NameTeam", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.TypeMark", "Updated_by", c => c.Int());
            AddColumn("dbo.TypeMark", "Updated_at", c => c.DateTime());
            AddColumn("dbo.TypeMark", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.TypeMark", "Created_at", c => c.DateTime());
            AddColumn("dbo.TypeMark", "NameTypeMark", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Parent", "Updated_by", c => c.Int());
            AddColumn("dbo.Parent", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Parent", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Parent", "Created_at", c => c.DateTime());
            AddColumn("dbo.Student", "Updated_by", c => c.Int());
            AddColumn("dbo.Student", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Student", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Student", "Created_at", c => c.DateTime());
            AddColumn("dbo.Conduct", "Updated_by", c => c.Int());
            AddColumn("dbo.Conduct", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Conduct", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Conduct", "Created_at", c => c.DateTime());
            AddColumn("dbo.StudentTranscript", "Updated_by", c => c.Int());
            AddColumn("dbo.StudentTranscript", "Updated_at", c => c.DateTime());
            AddColumn("dbo.StudentTranscript", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.StudentTranscript", "Created_at", c => c.DateTime());
            AddColumn("dbo.Classification", "Updated_by", c => c.Int());
            AddColumn("dbo.Classification", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Classification", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Classification", "Created_at", c => c.DateTime());
            AddColumn("dbo.Classification", "NameClassification", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Result", "Updated_by", c => c.Int());
            AddColumn("dbo.Result", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Result", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Result", "Created_at", c => c.DateTime());
            AddColumn("dbo.SchoolYear", "Updated_by", c => c.Int());
            AddColumn("dbo.SchoolYear", "Updated_at", c => c.DateTime());
            AddColumn("dbo.SchoolYear", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.SchoolYear", "Created_at", c => c.DateTime());
            AddColumn("dbo.Semester", "Updated_by", c => c.Int());
            AddColumn("dbo.Semester", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Semester", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Semester", "Created_at", c => c.DateTime());
            AddColumn("dbo.Semester", "SemesterName", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.SubjectMark", "Updated_by", c => c.Int());
            AddColumn("dbo.SubjectMark", "Updated_at", c => c.DateTime());
            AddColumn("dbo.SubjectMark", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.SubjectMark", "Created_at", c => c.DateTime());
            AddColumn("dbo.Subject", "Updated_by", c => c.Int());
            AddColumn("dbo.Subject", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Subject", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Subject", "Created_at", c => c.DateTime());
            AddColumn("dbo.Subject", "SubjectName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.DayOfWeekLesson", "Updated_by", c => c.Int());
            AddColumn("dbo.DayOfWeekLesson", "Updated_at", c => c.DateTime());
            AddColumn("dbo.DayOfWeekLesson", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.DayOfWeekLesson", "Created_at", c => c.DateTime());
            AddColumn("dbo.ScheduleSubject", "Updated_by", c => c.Int());
            AddColumn("dbo.ScheduleSubject", "Updated_at", c => c.DateTime());
            AddColumn("dbo.ScheduleSubject", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.ScheduleSubject", "Created_at", c => c.DateTime());
            AddColumn("dbo.Room", "Updated_by", c => c.Int());
            AddColumn("dbo.Room", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Room", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Room", "Created_at", c => c.DateTime());
            AddColumn("dbo.Grade", "Updated_by", c => c.Int());
            AddColumn("dbo.Grade", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Grade", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Grade", "Created_at", c => c.DateTime());
            AddColumn("dbo.Grade", "GradeName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Class", "Updated_by", c => c.Int());
            AddColumn("dbo.Class", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Class", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Class", "Created_at", c => c.DateTime());
            AddColumn("dbo.Class", "ClassName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Notification", "Updated_by", c => c.Int());
            AddColumn("dbo.Notification", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Notification", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Notification", "Created_at", c => c.DateTime());
            AddColumn("dbo.User", "Updated_by", c => c.Int());
            AddColumn("dbo.User", "Updated_at", c => c.DateTime());
            AddColumn("dbo.User", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.User", "Created_at", c => c.DateTime());
            AddColumn("dbo.Screen", "Updated_by", c => c.Int());
            AddColumn("dbo.Screen", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Screen", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Screen", "Created_at", c => c.DateTime());
            AddColumn("dbo.Screen", "ScreenName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Function", "Updated_by", c => c.Int());
            AddColumn("dbo.Function", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Function", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Function", "Created_at", c => c.DateTime());
            AddColumn("dbo.Function", "FunctionName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Permission", "Updated_by", c => c.Int());
            AddColumn("dbo.Permission", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Permission", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Permission", "Created_at", c => c.DateTime());
            AddColumn("dbo.Group", "Updated_by", c => c.Int());
            AddColumn("dbo.Group", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Group", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Group", "Created_at", c => c.DateTime());
            AddColumn("dbo.Group", "GroupName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Account", "Updated_by", c => c.Int());
            AddColumn("dbo.Account", "Updated_at", c => c.DateTime());
            AddColumn("dbo.Account", "Created_by", c => c.Int(nullable: false));
            AddColumn("dbo.Account", "Created_at", c => c.DateTime());
            AddColumn("dbo.Account", "Token", c => c.String(maxLength: 100));
            DropColumn("dbo.Slide", "UpdatedBy");
            DropColumn("dbo.Slide", "UpdatedAt");
            DropColumn("dbo.Slide", "CreatedBy");
            DropColumn("dbo.Slide", "CreatedAt");
            DropColumn("dbo.SchoolInformation", "UpdatedBy");
            DropColumn("dbo.SchoolInformation", "UpdatedAt");
            DropColumn("dbo.SchoolInformation", "CreatedBy");
            DropColumn("dbo.SchoolInformation", "CreatedAt");
            DropColumn("dbo.News", "UpdatedBy");
            DropColumn("dbo.News", "UpdatedAt");
            DropColumn("dbo.News", "CreatedBy");
            DropColumn("dbo.News", "CreatedAt");
            DropColumn("dbo.ErrorMessage", "UpdatedBy");
            DropColumn("dbo.ErrorMessage", "UpdatedAt");
            DropColumn("dbo.ErrorMessage", "CreatedBy");
            DropColumn("dbo.ErrorMessage", "CreatedAt");
            DropColumn("dbo.Teacher", "UpdatedBy");
            DropColumn("dbo.Teacher", "UpdatedAt");
            DropColumn("dbo.Teacher", "CreatedBy");
            DropColumn("dbo.Teacher", "CreatedAt");
            DropColumn("dbo.Team", "UpdatedBy");
            DropColumn("dbo.Team", "UpdatedAt");
            DropColumn("dbo.Team", "CreatedBy");
            DropColumn("dbo.Team", "CreatedAt");
            DropColumn("dbo.Team", "Name");
            DropColumn("dbo.TypeMark", "UpdatedBy");
            DropColumn("dbo.TypeMark", "UpdatedAt");
            DropColumn("dbo.TypeMark", "CreatedBy");
            DropColumn("dbo.TypeMark", "CreatedAt");
            DropColumn("dbo.TypeMark", "Name");
            DropColumn("dbo.Parent", "UpdatedBy");
            DropColumn("dbo.Parent", "UpdatedAt");
            DropColumn("dbo.Parent", "CreatedBy");
            DropColumn("dbo.Parent", "CreatedAt");
            DropColumn("dbo.Student", "UpdatedBy");
            DropColumn("dbo.Student", "UpdatedAt");
            DropColumn("dbo.Student", "CreatedBy");
            DropColumn("dbo.Student", "CreatedAt");
            DropColumn("dbo.Conduct", "UpdatedBy");
            DropColumn("dbo.Conduct", "UpdatedAt");
            DropColumn("dbo.Conduct", "CreatedBy");
            DropColumn("dbo.Conduct", "CreatedAt");
            DropColumn("dbo.StudentTranscript", "UpdatedBy");
            DropColumn("dbo.StudentTranscript", "UpdatedAt");
            DropColumn("dbo.StudentTranscript", "CreatedBy");
            DropColumn("dbo.StudentTranscript", "CreatedAt");
            DropColumn("dbo.Classification", "UpdatedBy");
            DropColumn("dbo.Classification", "UpdatedAt");
            DropColumn("dbo.Classification", "CreatedBy");
            DropColumn("dbo.Classification", "CreatedAt");
            DropColumn("dbo.Classification", "Name");
            DropColumn("dbo.Result", "UpdatedBy");
            DropColumn("dbo.Result", "UpdatedAt");
            DropColumn("dbo.Result", "CreatedBy");
            DropColumn("dbo.Result", "CreatedAt");
            DropColumn("dbo.SchoolYear", "UpdatedBy");
            DropColumn("dbo.SchoolYear", "UpdatedAt");
            DropColumn("dbo.SchoolYear", "CreatedBy");
            DropColumn("dbo.SchoolYear", "CreatedAt");
            DropColumn("dbo.Semester", "UpdatedBy");
            DropColumn("dbo.Semester", "UpdatedAt");
            DropColumn("dbo.Semester", "CreatedBy");
            DropColumn("dbo.Semester", "CreatedAt");
            DropColumn("dbo.Semester", "Name");
            DropColumn("dbo.SubjectMark", "UpdatedBy");
            DropColumn("dbo.SubjectMark", "UpdatedAt");
            DropColumn("dbo.SubjectMark", "CreatedBy");
            DropColumn("dbo.SubjectMark", "CreatedAt");
            DropColumn("dbo.Subject", "UpdatedBy");
            DropColumn("dbo.Subject", "UpdatedAt");
            DropColumn("dbo.Subject", "CreatedBy");
            DropColumn("dbo.Subject", "CreatedAt");
            DropColumn("dbo.Subject", "Name");
            DropColumn("dbo.DayOfWeekLesson", "UpdatedBy");
            DropColumn("dbo.DayOfWeekLesson", "UpdatedAt");
            DropColumn("dbo.DayOfWeekLesson", "CreatedBy");
            DropColumn("dbo.DayOfWeekLesson", "CreatedAt");
            DropColumn("dbo.ScheduleSubject", "UpdatedBy");
            DropColumn("dbo.ScheduleSubject", "UpdatedAt");
            DropColumn("dbo.ScheduleSubject", "CreatedBy");
            DropColumn("dbo.ScheduleSubject", "CreatedAt");
            DropColumn("dbo.Room", "UpdatedBy");
            DropColumn("dbo.Room", "UpdatedAt");
            DropColumn("dbo.Room", "CreatedBy");
            DropColumn("dbo.Room", "CreatedAt");
            DropColumn("dbo.Grade", "UpdatedBy");
            DropColumn("dbo.Grade", "UpdatedAt");
            DropColumn("dbo.Grade", "CreatedBy");
            DropColumn("dbo.Grade", "CreatedAt");
            DropColumn("dbo.Grade", "Name");
            DropColumn("dbo.Class", "UpdatedBy");
            DropColumn("dbo.Class", "UpdatedAt");
            DropColumn("dbo.Class", "CreatedBy");
            DropColumn("dbo.Class", "CreatedAt");
            DropColumn("dbo.Class", "Name");
            DropColumn("dbo.Notification", "UpdatedBy");
            DropColumn("dbo.Notification", "UpdatedAt");
            DropColumn("dbo.Notification", "CreatedBy");
            DropColumn("dbo.Notification", "CreatedAt");
            DropColumn("dbo.User", "UpdatedBy");
            DropColumn("dbo.User", "UpdatedAt");
            DropColumn("dbo.User", "CreatedBy");
            DropColumn("dbo.User", "CreatedAt");
            DropColumn("dbo.Screen", "UpdatedBy");
            DropColumn("dbo.Screen", "UpdatedAt");
            DropColumn("dbo.Screen", "CreatedBy");
            DropColumn("dbo.Screen", "CreatedAt");
            DropColumn("dbo.Screen", "Name");
            DropColumn("dbo.Function", "UpdatedBy");
            DropColumn("dbo.Function", "UpdatedAt");
            DropColumn("dbo.Function", "CreatedBy");
            DropColumn("dbo.Function", "CreatedAt");
            DropColumn("dbo.Function", "Name");
            DropColumn("dbo.Permission", "UpdatedBy");
            DropColumn("dbo.Permission", "UpdatedAt");
            DropColumn("dbo.Permission", "CreatedBy");
            DropColumn("dbo.Permission", "CreatedAt");
            DropColumn("dbo.Group", "UpdatedBy");
            DropColumn("dbo.Group", "UpdatedAt");
            DropColumn("dbo.Group", "CreatedBy");
            DropColumn("dbo.Group", "CreatedAt");
            DropColumn("dbo.Group", "Name");
            DropColumn("dbo.Account", "UpdatedBy");
            DropColumn("dbo.Account", "UpdatedAt");
            DropColumn("dbo.Account", "CreatedBy");
            DropColumn("dbo.Account", "CreatedAt");
            RenameIndex(table: "dbo.Teacher", name: "IX_TeamId", newName: "IX_IdTeam");
            RenameIndex(table: "dbo.Teacher", name: "IX_UserId", newName: "IX_IdUser");
            RenameIndex(table: "dbo.Parent", name: "IX_UserId", newName: "IX_IdUser");
            RenameIndex(table: "dbo.Student", name: "IX_ParentId", newName: "IX_IdParent");
            RenameIndex(table: "dbo.Student", name: "IX_ClassId", newName: "IX_IdClass");
            RenameIndex(table: "dbo.Student", name: "IX_UserId", newName: "IX_IdUser");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_SemesterId", newName: "IX_IdSemester");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_ConductId", newName: "IX_IdConduct");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_ClassificationId", newName: "IX_IdClassification");
            RenameIndex(table: "dbo.StudentTranscript", name: "IX_StudentId", newName: "IX_IdStudent");
            RenameIndex(table: "dbo.Result", name: "IX_ScholasticId", newName: "IX_IdScholastic");
            RenameIndex(table: "dbo.Result", name: "IX_ConductId", newName: "IX_IdConduct");
            RenameIndex(table: "dbo.Result", name: "IX_ClassificationId", newName: "IX_IdClassification");
            RenameIndex(table: "dbo.Result", name: "IX_StudentId", newName: "IX_IdStudent");
            RenameIndex(table: "dbo.Semester", name: "IX_ScholasticId", newName: "IX_IdScholastic");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_SemesterId", newName: "IX_IdSemester");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_SubjectId", newName: "IX_IdSubject");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_StudentId", newName: "IX_IdStudent");
            RenameIndex(table: "dbo.SubjectMark", name: "IX_TypeMarkId", newName: "IX_IdTypeMark");
            RenameIndex(table: "dbo.Subject", name: "IX_TeamId", newName: "IX_IdTeam");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_TeacherId", newName: "IX_IdTeacher");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_ClassId", newName: "IX_IdClass");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_SubjectId", newName: "IX_IdSubject");
            RenameIndex(table: "dbo.ScheduleSubject", name: "IX_DayLessonId", newName: "IX_IdDayLesson");
            RenameIndex(table: "dbo.Class", name: "IX_TeacherId", newName: "IX_IdTeacher");
            RenameIndex(table: "dbo.Class", name: "IX_RoomId", newName: "IX_IdRoom");
            RenameIndex(table: "dbo.Class", name: "IX_GradeId", newName: "IX_IdGrade");
            RenameIndex(table: "dbo.Notification", name: "IX_ClassReceiverId", newName: "IX_IdClassReceiver");
            RenameIndex(table: "dbo.Notification", name: "IX_ReceiverId", newName: "IX_IdReceiver");
            RenameIndex(table: "dbo.Notification", name: "IX_SenderId", newName: "IX_IdSender");
            RenameIndex(table: "dbo.Function", name: "IX_ScreenId", newName: "IX_IdScreen");
            RenameIndex(table: "dbo.Permission", name: "IX_FunctionId", newName: "IX_IdFunction");
            RenameIndex(table: "dbo.Permission", name: "IX_GroupId", newName: "IX_IdGroup");
            RenameIndex(table: "dbo.Account", name: "IX_GroupId", newName: "IX_IdGroup");
            RenameIndex(table: "dbo.Account", name: "IX_UserId", newName: "IX_IdUser");
            RenameColumn(table: "dbo.Teacher", name: "TeamId", newName: "IdTeam");
            RenameColumn(table: "dbo.Student", name: "ParentId", newName: "IdParent");
            RenameColumn(table: "dbo.StudentTranscript", name: "StudentId", newName: "IdStudent");
            RenameColumn(table: "dbo.StudentTranscript", name: "ConductId", newName: "IdConduct");
            RenameColumn(table: "dbo.StudentTranscript", name: "ClassificationId", newName: "IdClassification");
            RenameColumn(table: "dbo.Result", name: "StudentId", newName: "IdStudent");
            RenameColumn(table: "dbo.Result", name: "ConductId", newName: "IdConduct");
            RenameColumn(table: "dbo.Result", name: "ClassificationId", newName: "IdClassification");
            RenameColumn(table: "dbo.Result", name: "ScholasticId", newName: "IdScholastic");
            RenameColumn(table: "dbo.StudentTranscript", name: "SemesterId", newName: "IdSemester");
            RenameColumn(table: "dbo.Semester", name: "ScholasticId", newName: "IdScholastic");
            RenameColumn(table: "dbo.SubjectMark", name: "TypeMarkId", newName: "IdTypeMark");
            RenameColumn(table: "dbo.SubjectMark", name: "StudentId", newName: "IdStudent");
            RenameColumn(table: "dbo.SubjectMark", name: "SemesterId", newName: "IdSemester");
            RenameColumn(table: "dbo.Subject", name: "TeamId", newName: "IdTeam");
            RenameColumn(table: "dbo.SubjectMark", name: "SubjectId", newName: "IdSubject");
            RenameColumn(table: "dbo.ScheduleSubject", name: "TeacherId", newName: "IdTeacher");
            RenameColumn(table: "dbo.ScheduleSubject", name: "SubjectId", newName: "IdSubject");
            RenameColumn(table: "dbo.ScheduleSubject", name: "DayLessonId", newName: "IdDayLesson");
            RenameColumn(table: "dbo.Class", name: "TeacherId", newName: "IdTeacher");
            RenameColumn(table: "dbo.Student", name: "ClassId", newName: "IdClass");
            RenameColumn(table: "dbo.ScheduleSubject", name: "ClassId", newName: "IdClass");
            RenameColumn(table: "dbo.Class", name: "RoomId", newName: "IdRoom");
            RenameColumn(table: "dbo.Class", name: "GradeId", newName: "IdGrade");
            RenameColumn(table: "dbo.Notification", name: "ClassReceiverId", newName: "IdClassReceiver");
            RenameColumn(table: "dbo.Teacher", name: "UserId", newName: "IdUser");
            RenameColumn(table: "dbo.Student", name: "UserId", newName: "IdUser");
            RenameColumn(table: "dbo.Parent", name: "UserId", newName: "IdUser");
            RenameColumn(table: "dbo.Notification", name: "SenderId", newName: "IdSender");
            RenameColumn(table: "dbo.Notification", name: "ReceiverId", newName: "IdReceiver");
            RenameColumn(table: "dbo.Function", name: "ScreenId", newName: "IdScreen");
            RenameColumn(table: "dbo.Permission", name: "FunctionId", newName: "IdFunction");
            RenameColumn(table: "dbo.Permission", name: "GroupId", newName: "IdGroup");
            RenameColumn(table: "dbo.Account", name: "UserId", newName: "IdUser");
            RenameColumn(table: "dbo.Account", name: "GroupId", newName: "IdGroup");
        }
    }
}
